#! /usr/bin/env python3

import os
import jinja2

cwd = os.path.abspath(os.path.dirname(__file__))

path = [
    os.path.join(cwd, 'dir1'),
    os.path.join(cwd, 'dir2'),
]

loader = jinja2.FileSystemLoader(path)
gen = jinja2.Environment(loader=loader)
tpl = gen.get_template('foo/test')
